---
# Build a generic library
# params:
#   library_name: name of the library
#   library_url: download url of the library
#   working_folder: full path to the working folder
#   configure_command: default "configure"
#   skip_configure: true to skip the configure phase
#   skip_make: true to skip the make phase
#   skip_make_install: true to skip the make_install phase

- name: "download {{library_name}}"
  shell: chdir="{{working_folder}}"
         wget {{library_url}}

- name: "extract {{library_name}}"
  shell: chdir="{{working_folder}}"
         tar -zxf {{library_name}}.tar.gz

- name: "configure {{library_name}}"
  when: skip_configure is undefined and not skip_configure
  shell: |
    cd {{working_folder}}/{{library_name}}
    {{configure_command | default('./configure')}}
    make
    sudo make install
