---
# hspc_repo_api_mysql_project contains SQL files needed for install
- name: checkout repository hspc_repo_api_mysql_project
  tags: [api-stu3-all, api-stu3-code, smart-platform]
  become_user: "{{username}}"
  git: repo="{{api_stu3_repos_base}}/{{api_stu3_repo_api_mysql_project}}"
       version="{{api_stu3_repo_api_branch}}"
       dest="{{install_dir}}/hspc/api-stu3/{{api_stu3_repo_api_mysql_project}}"
       update={{update_repositories}}
       force=yes
       depth=1

- name: checkout repository hspc_repo_api_webapp_project
  tags: [api-stu3-all, api-stu3-code, smart-platform]
  become_user: "{{username}}"
  git: repo="{{hspc_repo_base}}/{{api_stu3_repo_api_webapp_project}}"
       version="{{api_stu3_repo_api_branch}}"
       dest="{{install_dir}}/hspc/api-stu3/{{api_stu3_repo_api_webapp_project}}"
       update={{update_repositories}}
       force=yes
       depth=1

- name: build hspc server api-stu3-server
  tags: [api-stu3-all, api-stu3-code, smart-platform]
  become_user: "{{username}}"
  shell: chdir={{install_dir}}/hspc/api-stu3/{{api_stu3_repo_api_webapp_project}}
       mvn clean install -e -U -Pjetty

- meta: flush_handlers