---
- name: "download the api_stu3 webapp"
  become_user: "{{hosting_username}}"
  include: "roles/common/tasks/download-maven-artifact.yml"
  vars:
    group_id: "{{api_stu3_server_artifact_group_id}}"
    artifact_id: "{{api_stu3_server_artifact_artifact_id}}"
    version: "{{api_stu3_server_artifact_version}}"
    packaging: "{{api_stu3_server_artifact_packaging}}"

- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file: "path={{item}} state=directory"
  with_items:
    - "{{hosting_user_home}}/api_stu3"

- name: "copy to the service directory"
  become_user: "{{hosting_username}}"
  copy:
    src: "{{api_stu3_server_artifact_location}}"
    dest: "{{hosting_user_home}}/api_stu3"
    remote_src: True

- name: "drop the api_stu3 database"
  mysql_db: name={{api_stu3_server_database}} state=absent

- name: "create the {{api_stu3_server_database}} database"
  mysql_db: name={{api_stu3_server_database}} state=present

# configure nginx
- name: "configure nginx (api_stu3)"
  template: src=api_stu3.j2 dest=/etc/nginx/sites-enabled/api_stu3 owner=root group=root mode=0644
  notify:
    - restart nginx

# configure the api_stu3 service
- name: "configure api_stu3 service"
  template: src=api_stu3.service.j2
            dest=/etc/systemd/system/api_stu3.service
            owner=root group=root mode=0644

- name: "enable api_stu3 service"
  shell: systemctl enable api_stu3.service

- name: "reload systemd daemon"
  shell: systemctl daemon-reload

- name: "restart api_stu3"
  service: name=api_stu3 state=restarted

- meta: flush_handlers

- name: "verify api_stu3 is available"
  become_user: "{{hosting_username}}"
  wait_for: host={{api_stu3_server_internal_host}} port={{api_stu3_server_port}}

- meta: flush_handlers

# SMART production only
- name: drop sandbox snapshot
  when: enable_nightly_reset
  include: roles/common/tasks/snapshot-command.yml
  vars:
    sandbox_url: "{{api_stu3_server_local_default_sandbox_url}}"
    snapshot_name: "{{api_stu3_baseline_snapshot}}"
    snapshot_action: Delete

- name: take baseline snapshot
  become_user: "{{hosting_username}}"
  when: enable_nightly_reset
  include: roles/common/tasks/snapshot-command.yml
  vars:
    sandbox_url: "{{api_stu3_server_local_default_sandbox_url}}"
    snapshot_name: "{{api_stu3_baseline_snapshot}}"
    snapshot_action: Take

- name: "create script restore-baseline-snapshot-stu3.sh"
  when: enable_nightly_reset
  become_user: "{{hosting_username}}"
  template: src=restore-baseline-snapshot-stu3.sh.j2
            dest={{user_scripts_home}}/restore-baseline-snapshot-stu3.sh
            mode=0755

- name: "create script reset-database-job.sh"
  when: enable_nightly_reset
  become_user: "{{hosting_username}}"
  template: src=reset-database-job-stu3.sh.j2
            dest={{user_scripts_home}}/reset-database-job-stu3.sh
            mode=0755

# create a cron job for nightly reset to be run at 5 AM UTC, or midnight US-EST
- name: "create cron job to nightly reset the api database"
  when: enable_nightly_reset
  become_user: "{{hosting_username}}"
  cron:
    name: "reset api_stu3 database"
    minute: "0"
    hour: "5"
    job: "{{user_scripts_home}}/reset-database-job-stu3.sh >> {{user_jobs_output_home}}/nightly-reset.log"

# Persona server
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file: "path={{item}} state=directory"
  with_items:
    - "{{hosting_user_home}}/persona_api_stu3"

- name: "copy to the service directory"
  become_user: "{{hosting_username}}"
  copy:
    src: "{{api_stu3_server_artifact_location}}"
    dest: "{{hosting_user_home}}/persona_api_stu3"
    remote_src: True

# configure nginx
- name: "configure nginx (persona_api_stu3)"
  template: src=persona_api_stu3.j2 dest=/etc/nginx/sites-enabled/persona_api_stu3 owner=root group=root mode=0644
  notify:
    - restart nginx

# configure the persona_api_stu3 service
- name: "configure persona_api_stu3 service"
  template: src=persona_api_stu3.service.j2
            dest=/etc/systemd/system/persona_api_stu3.service
            owner=root group=root mode=0644

- name: "enable persona_api_stu3 service"
  shell: systemctl enable persona_api_stu3.service

- name: "reload systemd daemon"
  shell: systemctl daemon-reload

- name: "restart persona_api_stu3"
  service: name=persona_api_stu3 state=restarted

- meta: flush_handlers

- name: "verify persona_api_stu3 is available"
  become_user: "{{hosting_username}}"
  wait_for: host={{persona_api_stu3_server_internal_host}} port={{persona_api_stu3_server_port}}

- meta: flush_handlers

# Mock server
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file: "path={{item}} state=directory"
  with_items:
    - "{{hosting_user_home}}/mock_api_stu3"

- name: "copy to the service directory"
  become_user: "{{hosting_username}}"
  copy:
    src: "{{api_stu3_server_artifact_location}}"
    dest: "{{hosting_user_home}}/mock_api_stu3"
    remote_src: True

# configure nginx
- name: "configure nginx (mock_api_stu3)"
  template: src=mock_api_stu3.j2 dest=/etc/nginx/sites-enabled/mock_api_stu3 owner=root group=root mode=0644
  notify:
    - restart nginx

# configure the mock_api_stu3 service
- name: "configure mock_api_stu3 service"
  template: src=mock_api_stu3.service.j2
            dest=/etc/systemd/system/mock_api_stu3.service
            owner=root group=root mode=0644

- name: "enable mock_api_stu3 service"
  shell: systemctl enable mock_api_stu3.service

- name: "reload systemd daemon"
  shell: systemctl daemon-reload

- name: "restart mock_api_stu3"
  service: name=mock_api_stu3 state=restarted

- meta: flush_handlers

- name: "verify mock_api_stu3 is available"
  become_user: "{{hosting_username}}"
  wait_for: host={{mock_api_stu3_server_internal_host}} port={{mock_api_stu3_server_port}}

- meta: flush_handlers
