---
- hosts: all:!REMOTEHOST
  become: yes
  vars_files:
    - settings.yml
    - custom_settings.yml
  roles:
    - apacheds-code
    - pwm-code
    - api-dstu2-code
    - apps-code
    - messaging-code
    - sandbox-manager-code
    - auth-code

- hosts: REMOTEHOST
  remote_user: "{{installer_user}}"
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  vars_files:
    - settings.yml
    - custom_settings.yml
  roles:
    - apacheds-code
    - pwm-code
    - api-dstu2-code
    - apps-code
    - messaging-code
    - sandbox-manager-code
    - auth-code
