---
- name: checkout repository messaging_project
  tags: [messaging-all, messaging-code, smart-platform]
  become_user: "{{hosting_username}}"
  git: repo="{{hspc_repo_base}}/{{messaging_project}}"
       version="{{messaging_branch}}"
       dest="{{hosting_user_home}}/{{messaging_project}}"
       update={{update_repositories}}
       force=yes
       depth=1

- name: build hspc messaging server
  tags: [messaging-all, messaging-code, smart-platform]
  become_user: "{{hosting_username}}"
  shell: chdir={{hosting_user_home}}
       mvn clean install -e -U -f reference-messaging/pom.xml
