---
- name: Configure MySQL user
  tags: [sandbox-manager-all, sandbox-manager-data, smart-platform]
  mysql_user: name={{mysql_username}} host={{mysql_host}} password={{mysql_password}} priv={{mysql_privilage}} state=present

- name: Drop the sandbox-manager-server database
  tags: [sandbox-manager-all, sandbox-manager-data, smart-platform]
  mysql_db: name={{sandman_server_database}} state=absent

- name: Create the sandbox-manager-server database
  tags: [sandbox-manager-all, sandbox-manager-data, smart-platform]
  mysql_db: name={{sandman_server_database}} state=present

- name: patch sandbox manager create
  tags: [sandbox-manager-all, sandbox-manager-data, smart-platform]
  become_user: "{{hosting_username}}"
  template: src=create-sandman.sql.j2
             dest={{hosting_user_home}}/sandbox-manager/src/main/resources/db/create-sandman.sql

- name: patch sandbox manager install
  tags: [sandbox-manager-all, sandbox-manager-data, smart-platform]
  become_user: "{{hosting_username}}"
  template: src=initialize-sandman.sql.j2
            dest={{hosting_user_home}}/sandbox-manager/src/main/resources/db/initialize-sandman.sql

- name: create the sandbox manager database
  tags: [sandbox-manager-all, sandbox-manager-data, smart-platform]
  mysql_db: name={{sandman_server_database}} state=import target="{{hosting_user_home}}/sandbox-manager/src/main/resources/db/create-sandman.sql"

- name: initialize the sandbox manager database
  tags: [sandbox-manager-all, sandbox-manager-data, smart-platform]
  mysql_db: name={{sandman_server_database}} state=import target="{{hosting_user_home}}/sandbox-manager/src/main/resources/db/initialize-sandman.sql"
