---
- name: Configure MySQL user
  tags: [auth-all, auth-data, smart-platform]
  mysql_user: name={{mysql_user}} host=localhost password={{mysql_pass}} priv={{mysql_privilage}} state=present

- name: Drop the Authorization Server database
  tags: [auth-all, auth-data, smart-platform]
  mysql_db: name={{auth_server_database}} state=absent

- name: Create the Authorization Server database
  tags: [auth-all, auth-data, smart-platform]
  mysql_db: name={{auth_server_database}} state=present

- name: clear auth server data
  tags: [auth-all, auth-data, smart-platform]
  file: path={{auth_db_file}}{{item}} state=absent
# todo figure this out
#   when: not auth_server_preserve_db
  with_items: [".tmp", ".properties", ".script", ".log", ""]

- name: install client scripts
  tags: [auth-all, auth-data, smart-platform]
  template: src="{{item}}.j2" dest="{{hspc_install_dir}}/{{auth_webapp_project}}/src/main/resources/db/openidconnect/mysql/{{item}}"
  with_items:
    - "mysql_database_tables.sql"
    - "mysql_users.sql"
    - "mysql_system_scopes.sql"
    - "mysql_clients.sql"
    - "sandbox-manager-client.sql"
    - "patient-picker-client.sql"
    - "resource-server-client.sql"

- name: load clients
  tags: [auth-all, auth-data, smart-platform]
  mysql_db: name={{auth_server_database}} state=import target="{{hspc_install_dir}}/{{auth_webapp_project}}/src/main/resources/db/openidconnect/mysql/{{item}}"
  with_items:
    - "mysql_database_tables.sql"
    - "mysql_users.sql"
    - "mysql_system_scopes.sql"
    - "mysql_clients.sql"
    - "sandbox-manager-client.sql"
    - "patient-picker-client.sql"
    - "resource-server-client.sql"

- meta: flush_handlers
