---
- name: "generate sandbox admin update script"
  become_user: "{{hosting_username}}"
  template: src="update-sandbox-admin-password.ldif.j2"
            dest="{{apacheds_home}}/update-sandbox-admin-password.ldif"

- name: "update sandbox admin"
  become_user: "{{hosting_username}}"
  shell: chdir={{apacheds_home}}
         ldapadd
           -h {{apacheds_server_external_host}}
           -p {{apacheds_server_external_port}}
           -x -D {{apacheds_server_system_admin_dn}}
           -w {{apacheds_server_system_admin_initial_password}}
           -f update-sandbox-admin-password.ldif
  failed_when: False

- name: "generate sandbox demo update script"
  become_user: "{{hosting_username}}"
  template: src="update-sandbox-demo-password.ldif.j2"
            dest="{{apacheds_home}}/update-sandbox-demo-password.ldif"

- name: "update sandbox demo"
  become_user: "{{hosting_username}}"
  shell: chdir={{apacheds_home}}
         ldapadd
           -h {{apacheds_server_external_host}}
           -p {{apacheds_server_external_port}}
           -x -D {{apacheds_server_system_admin_dn}}
           -w {{apacheds_server_system_admin_initial_password}}
           -f update-sandbox-demo-password.ldif
  failed_when: False

