---
- name: "check custom certificate preconditions"
  fail: msg="please define the path to the custom certificates that you would like to use"
  when: use_custom_ssl_certificates and (custom_ssl_certificates_path is not defined)

- name: "remove existing apacheds installation"
  become_user: "{{hosting_username}}"
  file: path="{{apacheds_home}}" state=absent

# for raw apacheds
#- name: download apacheds
#  tags: [apacheds-all, apacheds-server, smart-platform]
#  become_user: "{{hosting_username}}"
#  get_url: url={{apacheds_artifact_url}} dest={{hosting_user_home}}
#
#- name: extract apacheds
#  tags: [apacheds-all, apacheds-server, smart-platform]
#  become_user: "{{hosting_username}}"
#  unarchive: src="{{hosting_user_home}}/{{apacheds_artifact_name}}" dest="{{hosting_user_home}}" copy=no
#
#- name: setenv.sh properties
#  tags: [apacheds-all, apacheds-server, smart-platform]
#  template: src=setenv.sh.j2 dest="{{apacheds_home}}/bin/setenv.sh" owner="{{hosting_username}}" group="{{hosting_username}}" mode=0744
#
- name: "extract configured apacheds"
  become_user: "{{hosting_username}}"
  unarchive: src="apacheds-2.0.0-M23-configured.tar" dest="{{hosting_user_home}}"

