---
# *** Main configuration file for the API-DSTU2 Installer ***
api_dstu2_server_initial_memory: 128M
api_dstu2_server_max_memory: 256M

# Artifacts
api_dstu2_webapp_info:
  group_id: "org.hspconsortium.reference"
  artifact_id: "hspc-reference-api-webapp-multitenant"
  version: "1.4.2"
  packaging: "war"
  war_location: "{{m2_repo_folder}}/org/hspconsortium/reference/hspc-reference-api-webapp-multitenant/1.4.2"

api_dstu2_database: "hspc_{{api_dstu2_schema_version}}_{{api_dstu2_server_smart_sandbox}}"
api_dstu2_baseline_snapshot: initial
api_dstu2_mysql_privilage: "{{api_dstu2_database}}.*:ALL/*.*:ALL,GRANT"

# General settings for the sample patients set
api_dstu2_sample_patients_repo: "https://github.com/smart-on-fhir/sample-patients.git"
api_dstu2_sample_patients_branch: "master"

# General settings for the custom-sample-data
api_dstu2_custom_sample_data_repo: "https://github.com/smart-on-fhir/custom-sample-data.git"
api_dstu2_custom_sample_data_branch: "master"

# choose how many sample patients to load in the server or set to 9999 for all of them
api_dstu2_sample_patients_limit: 20
api_dstu2_include_custom_patients: false

# Additional parameters for the sample patient generator
api_dstu2_sample_patients_generator_params: ""

# DSTU2 API Server settings
api_dstu2_server_internal_host: localhost
api_dstu2_server_internal_port: 8070
api_dstu2_server_internal_base_url: "http://{{api_dstu2_server_internal_host}}:{{api_dstu2_server_internal_port}}{{api_dstu2_server_context}}"
api_dstu2_server_internal_smart_sandbox_url: "{{api_dstu2_server_internal_base_url}}{{api_dstu2_server_smart_sandbox}}"
api_dstu2_server_internal_smart_sandbox_fhir_root_url: "{{api_dstu2_server_internal_smart_sandbox_url}}/data"
api_dstu2_server_internal_smart_sandbox_open_fhir_root_url: "{{api_dstu2_server_internal_smart_sandbox_url}}/open"

# PERSONA DSTU2 API Server settings
persona_api_dstu2_server_internal_host: localhost
persona_api_dstu2_server_internal_port: 8071
persona_api_dstu2_server_internal_base_url: "http://{{persona_api_dstu2_server_internal_host}}:{{persona_api_dstu2_server_internal_port}}{{persona_api_dstu2_server_context}}"
persona_api_dstu2_server_internal_smart_sandbox_url: "{{persona_api_dstu2_server_internal_base_url}}{{persona_api_dstu2_server_smart_sandbox}}"
persona_api_dstu2_server_internal_smart_sandbox_fhir_root_url: "{{persona_api_dstu2_server_internal_smart_sandbox_url}}/data"
persona_api_dstu2_server_internal_smart_sandbox_open_fhir_root_url: "{{persona_api_dstu2_server_internal_smart_sandbox_url}}/open"

# MOCK DSTU2 API Server settings
mock_api_dstu2_server_internal_host: localhost
mock_api_dstu2_server_internal_port: 8074
mock_api_dstu2_server_internal_base_url: "http://{{mock_api_dstu2_server_internal_host}}:{{mock_api_dstu2_server_internal_port}}{{mock_api_dstu2_server_context}}"
mock_api_dstu2_server_internal_smart_sandbox_url: "{{mock_api_dstu2_server_internal_base_url}}{{mock_api_dstu2_server_smart_sandbox}}"
mock_api_dstu2_server_internal_smart_sandbox_fhir_root_url: "{{mock_api_dstu2_server_internal_smart_sandbox_url}}/data"
mock_api_dstu2_server_internal_smart_sandbox_open_fhir_root_url: "{{mock_api_dstu2_server_internal_smart_sandbox_url}}/open"

# Set this to either "open" or "secured" on the primary endpoint /data
api_dstu2_server_security_mode: secured
# Set this to none to remove open access
api_dstu2_server_open_access_endpoint: open
# Set this to "mock" on the primary endpoint /data
mock_api_dstu2_server_security_mode: mock


