---
- name: "create the service directory"
  become_user: "{{hosting_username}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{hosting_user_home}}/patient_picker"

- name: "check out patient_picker project"
  git:
    repo: "{{hspc_repo_base}}/patient-picker.git"
    dest: "{{hosting_user_home}}/patient_picker"
    version: "{{patient_picker_project_version}}"

- name: "install patient_picker system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "patient_picker"
    service_definition_file: "roles/patient_picker/templates/patient_picker.service.j2"
    gateway_definition_file: "roles/patient_picker/templates/patient_picker.j2"
    internal_port: "{{patient_picker_server_internal_port}}"
    external_host: "{{patient_picker_server_external_host}}"
    external_port: "{{patient_picker_server_external_port}}"
