---
- hosts: all:!REMOTEHOST
  become: yes
  vars_files:
    - global_settings.yml
    - custom_settings.yml
  roles:
    - apacheds-common
    - apacheds-sandbox
    - pwm-common
    - pwm-sandbox
    - api-dstu2-common
    - api-dstu2-sandbox

- hosts: REMOTEHOST
  remote_user: "{{installer_user}}"
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  vars_files:
    - global_settings.yml
    - custom_settings.yml
  roles:
    - apacheds-common
    - apacheds-sandbox
    - pwm-common
    - pwm-sandbox
    - api-dstu2-common
    - api-dstu2-sandbox
