---
- hosts: all:!REMOTEHOST
  become: yes
  vars_files:
    - settings.yml
    - settings_auth.yml
    - settings_api.yml
    - settings_apps.yml
    - settings_sandman.yml
    - settings_apacheds.yml
  roles:
    - common
    - auth

- hosts: REMOTEHOST
  remote_user: "{{installer_user}}"
  gather_facts: yes
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  vars_files:
    - settings.yml
    - settings_auth.yml
    - settings_api.yml
    - settings_apps.yml
    - settings_sandman.yml
    - settings_apacheds.yml
  roles:
    - common
    - auth
