---
- hosts: all:!REMOTEHOST
  become: yes
  vars_files:
    - global_settings.yml
    - custom_settings.yml
  roles:
    - common
    - apacheds-server
    - pwm-server
    - api-dstu2-server
    - apps-server
    - messaging-server
    - sandbox-manager-server
    - auth-server

- hosts: REMOTEHOST
  remote_user: "{{installer_user}}"
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  vars_files:
    - global_settings.yml
    - custom_settings.yml
  roles:
    - common
    - apacheds-server
    - pwm-server
    - api-dstu2-server
    - apps-server
    - messaging-server
    - sandbox-manager-server
    - auth-server
