---
- hosts: all:!REMOTEHOST
  become: yes
  vars_files:
    - settings.yml
    - settings_api.yml
    - settings_auth.yml
    - settings_messaging.yml
  roles:
    - common
    - api

- hosts: REMOTEHOST
  remote_user: "{{installer_user}}"
  gather_facts: yes
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  vars_files:
    - settings.yml
    - settings_api.yml
    - settings_auth.yml
    - settings_messaging.yml
  roles:
    - common
    - api
