---
- hosts: all:!REMOTEHOST
  become: yes
  vars_files:
    - global_settings.yml
    - custom_settings.yml
  roles:
    - pwm-common
    - pwm-data
    - api-dstu2-common
    - api-dstu2-data
    - sandbox-manager-common
    - sandbox-manager-data
    - auth-common
    - auth-data

- hosts: REMOTEHOST
  remote_user: "{{installer_user}}"
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  vars_files:
    - global_settings.yml
    - custom_settings.yml
  roles:
    - pwm-common
    - pwm-data
    - api-dstu2-common
    - api-dstu2-data
    - sandbox-manager-common
    - sandbox-manager-data
    - auth-common
    - auth-data
