---
# messaging artifact
messaging_server_artifact_group_id: "org.hspconsortium.reference"
messaging_server_artifact_artifact_id: "hspc-reference-messaging"
messaging_server_artifact_version: "1.3.0"
messaging_server_artifact_packaging: "jar"
messaging_server_artifact_repository_url: "{{release_repository_url}}"
messaging_server_internal_host: "localhost"
messaging_server_internal_port: "8091"
messaging_server_external_host: "{{services_host | default(localhost)}}"
messaging_server_external_port: "9091"
messaging_server_external_url: "{{http_protocol}}://{{messaging_server_external_host}}:{{messaging_server_external_port}}"
messaging_server_initial_memory: 64M
messaging_server_max_memory: 128M
messaging_profiles: test
messaging_mail_server_username:
messaging_mail_server_password:
