---
# sandman artifact
sandman_server_artifact_group_id: "org.hspconsortium.sandbox"
sandman_server_artifact_artifact_id: "hspc-sandbox-manager"
sandman_server_artifact_version: "1.7.0-SNAPSHOT"
sandman_server_artifact_packaging: "war"
sandman_server_artifact_repository_url: "{{snapshot_repository_url}}"
sandman_server_database: "sandman"
sandman_server_internal_host: "localhost"
sandman_server_internal_port: "8080"
sandman_server_external_host: "{{services_host | default(localhost)}}"
sandman_server_external_port: "9080"
sandman_server_external_url: "{{http_protocol}}://{{sandman_server_external_host}}:{{sandman_server_external_port}}"
sandman_server_initial_memory: "128M"
sandman_server_max_memory: "256M"
sandman_server_env: "prod"
sandman_server_send_email: "false"
sandman_server_default_sandbox_creator_roles: "ADMIN,MANAGE_USERS,MANAGE_DATA"
sandman_server_default_system_roles: "USER"
sandman_server_default_private_sandbox_roles: "USER,MANAGE_USERS,MANAGE_DATA"
sandman_server_default_sandbox_visibility: "PUBLIC"
sandman_server_default_public_sandbox_roles: "USER"
sandbox_server_admin_access_client_id: "sandman_admin"
sandbox_server_admin_access_client_secret: "changeme"
#sandman_mysql_reset_database: false
sandman_server_api_v1_url: "{{api_dstu2_server_external_url}}"
sandman_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v3_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v4_url: "{{api_stu3_server_external_url}}"
sandman_company_logo_path: "static/branding/smart/images/smart-logo.png"
sandman_company_logo2x_path: "static/branding/smart/images/smart-logo@2x.png"
