---
#- include: playbook_linux.yml
#
#- include: playbook_apacheds.yml
#
#- include: playbook_pwm.yml
#
- include: playbook_auth.yml
#
#- include: playbook_api_dstu2.yml
#
#- include: playbook_api_stu3.yml
#
#- include: playbook_messaging.yml
#
#- include: playbook_apps.yml
#
- include: playbook_sandbox_manager.yml

