---
- include: playbook-linux.yml

- include: playbook-apacheds.yml

- include: playbook-pwm.yml

- include: playbook-auth.yml

- include: playbook-api-dstu2.yml

- include: playbook-api-dstu3.yml

- include: playbook-messaging.yml

- include: playbook-apps.yml

- include: playbook-sandbox-manager.yml

