---
- name: "configure apacheds-server service"
  template: src=apacheds-server.service.j2
            dest=/etc/systemd/system/apacheds-server.service
            owner=root group=root mode=0644

- name: "enable apacheds-server service"
  shell: systemctl enable apacheds-server.service

- name: "reload systemd daemon"
  shell: systemctl daemon-reload

- name: "stop apacheds-server"
  service: name=apacheds-server state=stopped

- meta: flush_handlers

- name: "restart apacheds-server"
  service: name=apacheds-server enabled=yes state=restarted

- name: "verify apacheds-server is available"
  wait_for: host={{apacheds_server_internal_host}} port={{apacheds_server_internal_port}}
