---
# Builds a nginx server that supports ngx_http_sub_module
- name: "create the project directory"
  file: "path={{item}} state=directory"
  with_items:
    - "{{installer_user_home}}/nginx"

- name: "create the service directory"
  file: "path={{item}} state=directory mode=0755"
  with_items:
    - "/etc/nginx"
    - "/etc/nginx/conf.d"
    - "/etc/nginx/sites-available"
    - "/etc/nginx/sites-enabled"
    - "/etc/nginx/snippets"
    - "/var/log/nginx"

- name: "Check for installation of pcre"
  stat: "path={{installer_user_home}}/nginx/pcre-8.40"
  register: pcre_installed

- name: "install pcre"
#  when: not pcre_installed.stat.exists
  include: "roles/common/tasks/build_library_template.yml"
  vars:
    library_name: "pcre-8.40"
    library_url: "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.40.tar.gz"
    working_folder: "{{installer_user_home}}/nginx"

- name: "Check for installation of zlib-1.2.11"
  stat: "path={{installer_user_home}}/nginx"
  register: zlib_instaled

- name: "install zlib-1.2.11"
#  when: not zlib_instaled.stat.exists
  include: "roles/common/tasks/build_library_template.yml"
  vars:
    library_name: "zlib-1.2.11"
    library_url: "http://zlib.net/zlib-1.2.11.tar.gz"
    working_folder: "{{installer_user_home}}/nginx"

- name: "Check for installation of openssl-1.0.2f"
  stat: "path={{installer_user_home}}/nginx/openssl-1.0.2f"
  register: openssl_installed

- name: "install openssl-1.0.2f"
#  when: not openssl_installed.stat.exists
  include: "roles/common/tasks/build_library_template.yml"
  vars:
    library_name: "openssl-1.0.2f"
    library_url: "http://www.openssl.org/source/openssl-1.0.2f.tar.gz"
    working_folder: "{{installer_user_home}}/nginx"
    configure_command: "./config --prefix=/usr/local --openssldir=/usr/local/openssl"

#- name: "Check for installation of nginx-1.11.13"
#  stat: "path={{installer_user_home}}/nginx/nginx-1.11.13/nginx-1.11.13"
#  register: nginx_instaled
#
#- include: nginx.yml
#  when: not p.stat.exists

- name: "install nginx-1.11.13"
  include: "roles/common/tasks/build_library_template.yml"
  vars:
    library_name: "nginx-1.11.13"
    library_url: "http://nginx.org/download/nginx-1.11.13.tar.gz"
    working_folder: "{{installer_user_home}}/nginx"
    configure_command: "./configure --prefix=/usr --with-http_ssl_module --with-http_sub_module"

- name: "install nginx system"
  include: "roles/common/tasks/service_template.yml"
  vars:
    service_name: "nginx"
    service_definition_file: "roles/linux/templates/nginx.service.j2"
    internal_host: "localhost"
    internal_port: "80"
